### ISSUE TITLE
Poke method?

### ISSUE THREAD

**Issue by PSeitz** [maidsafe/lru_time_cache#100]
My lru_time_cache is behind a RwLock, so the get method needs to be in a write() lock. To avoid this I could get() a result drop it and then peek it, but a poke/peek method or something like that would be nicer.

**Comment by dirvine** [comment]
There are some incoming changes that may help you here. Maybe @povilasb  can help? Let's see though.

**Comment by povilasb** [comment]
Hey, there's already a [peek()](https://github.com/maidsafe/lru_time_cache/blob/master/src/lib.rs#L372) method:
```
    /// Returns a reference to the value with the given `key`, if present and not expired, without
    /// updating the timestamp.
    pub fn peek<Q: ?Sized>(&self, key: &Q) -> Option<&Value>
```

It won't require `RwLock::write()`. 
Or is it smth else you're looking for?

**Comment by PSeitz** [comment]
The peek method doesn't update the timestamp. I want to update the timestamp, without keeping the write-lock all the time. Currently I use get, drop and then peek.

**Comment by povilasb** [comment]
So you want to modify `LruCache` without the `write` lock? Won't that be a race condition that `RwLock` is trying to prevent you from? :)

**Comment by PSeitz** [comment]
I just want to update the timestamp, not the contents of LruCache. Here's how I do it now, to avoid keeping a write lock, in the big scope. A poke method would be nice to just update the timestamp.

```rust
{
    cache.write().get("blub"); // update the timestamp
}
//get the reference
let el = cache.read().peek("blub");

```


 `pub fn get<Q: ?Sized>(&self, key: &Q)` would also be possible if the timestamp is guarded internally, altough that may be undesired.
```rust
let el = cache.read().get("blub"); // updates the timestamp, gets ref
```

**Comment by povilasb** [comment]
Unfortunately, this is not practical.

1. Currently we cannot make `get()` immutable (so `read()` lock would suffice) because internally it does two mutations: remove expired items and update the timestamp of item associated with get key.
2. Technically we could synchronize those mutations inside `LruCache` but this is not what I'd be looking for this library. That would result in synchronization overhead every time the `LruCache` is used. 

Currently `LruCache` is not thread safe and it's up to it's users to provide safety. Personally, I would leave it this way as it's most flexible.

**Comment by S-Coyle** [comment]
Closing as issue has been stagnant for some time
